[package]
name = "cf-workers-raw"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
once_cell = "1"
urlencoding = "2"
worker = { version = "0.5", features = ["http"] }
