name = "userscripts-cf-proxy"
main = "build/worker/shim.mjs"
compatibility_date = "2025-11-17"
keep_vars = true

[build]
command = "mise run build"

# Default: userscripts
[vars]
GH_NAME = "udmada"
GH_REPO = "userscripts"
GH_BRANCH = "master"

# Userstyles environment
[env.userstyles]
name = "userstyles-proxy"
[env.userstyles.vars]
GH_NAME = "udmada"
GH_REPO = "userstyles"
GH_BRANCH = "master"

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1
