name = "userscripts-cf-proxy"
main = "build/worker/shim.mjs"
compatibility_date = "2025-11-17"
keep_vars = true

[build]
command = "mise run build"

[build.upload]
format = "modules"

[vars]
GH_NAME = "udmada"
GH_REPO = "userscripts"
GH_BRANCH = "master"
